inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true
  
Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Layout/FirstHashElementLineBreak:
  Enabled: false

Airbnb/OptArgParameters:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/MutableConstant:
  Enabled: false
  
Metrics/LineLength:
  Enabled: false

Layout/AlignArguments:
  Enabled: false

Layout/BlockAlignment:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/SpaceAfterColon:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false
  
Layout/EmptyLines:
  Enabled: false
  
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/BlockComments:
  Enabled: false